"""
playlist_manager.py — YouTube kanalında tematik playlist yönetimi.

Video yüklendikten sonra ilgili playlist'e otomatik ekler.
Playlist yoksa oluşturur.

Playlist'ler script'teki tag'lere göre belirlenir:
  - "rome", "greek", "persian" → "Ancient World"
  - "ww2", "world war", "nazi" → "World War II"
  - "napoleon", "french" → "European History"
  - vs. → "What If History" (varsayılan)

Gereksinim: YOUTUBE_TOKEN_JSON
"""

import json
import os
import re
import tempfile

try:
    from googleapiclient.discovery import build
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request
    YOUTUBE_AVAILABLE = True
except ImportError:
    YOUTUBE_AVAILABLE = False


SCOPES = ["https://www.googleapis.com/auth/youtube"]

PLAYLIST_STATE_PATH = "playlist_ids.json"

# Konu → Playlist eşleşme kuralları (öncelik sırasıyla)
PLAYLIST_RULES = [
    {
        "name": "Ancient World — What If?",
        "keywords": ["rome", "roman", "greek", "persia", "persian", "egypt", "egyptian",
                     "babylon", "carthage", "sparta", "athens", "julius caesar", "alexander"],
    },
    {
        "name": "World War II — Alternate History",
        "keywords": ["ww2", "world war 2", "world war ii", "nazi", "hitler", "d-day",
                     "normandy", "stalingrad", "pacific war", "pearl harbor"],
    },
    {
        "name": "World War I — What If?",
        "keywords": ["ww1", "world war 1", "world war i", "great war", "trench",
                     "western front", "ottoman"],
    },
    {
        "name": "Medieval History — Alternate Paths",
        "keywords": ["medieval", "middle ages", "crusade", "crusades", "mongol",
                     "genghis khan", "viking", "feudal", "black death", "plague"],
    },
    {
        "name": "American History — What If?",
        "keywords": ["american", "civil war", "confederate", "union", "revolutionary war",
                     "washington", "lincoln", "colonial"],
    },
    {
        "name": "Cold War — Alternate Scenarios",
        "keywords": ["cold war", "soviet", "ussr", "nuclear", "cuban missile",
                     "korean war", "vietnam", "space race"],
    },
    {
        "name": "What If History",   # Varsayılan — her video buraya girer
        "keywords": [],
    },
]


def _get_credentials() -> "Credentials":
    token_json = os.environ.get("YOUTUBE_TOKEN_JSON")
    if token_json:
        data = json.loads(token_json)
        tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False)
        json.dump(data, tmp)
        tmp.close()
        creds = Credentials.from_authorized_user_file(tmp.name, SCOPES)
        os.unlink(tmp.name)
    elif os.path.exists("token.json"):
        creds = Credentials.from_authorized_user_file("token.json", SCOPES)
    else:
        raise FileNotFoundError("YouTube token bulunamadı.")
    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
    return creds


def _load_playlist_cache() -> dict:
    if os.path.exists(PLAYLIST_STATE_PATH):
        with open(PLAYLIST_STATE_PATH, encoding="utf-8") as f:
            return json.load(f)
    return {}


def _save_playlist_cache(cache: dict) -> None:
    with open(PLAYLIST_STATE_PATH, "w", encoding="utf-8") as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)


def _get_or_create_playlist(youtube, name: str, cache: dict) -> str:
    """
    Playlist varsa ID'sini döndürür, yoksa oluşturur.
    Cache ile API çağrısı minimuma indirilir.
    """
    if name in cache:
        return cache[name]

    # Kanal playlist'lerini listele
    try:
        resp = youtube.playlists().list(
            part="snippet",
            mine=True,
            maxResults=50,
        ).execute()
        for item in resp.get("items", []):
            pname = item["snippet"]["title"]
            cache[pname] = item["id"]
            if pname == name:
                _save_playlist_cache(cache)
                return item["id"]
    except Exception as e:
        print(f"[playlist] Playlist listesi alınamadı: {e}")

    # Bulunamadıysa oluştur
    try:
        result = youtube.playlists().insert(
            part="snippet,status",
            body={
                "snippet": {
                    "title": name,
                    "description": (
                        f"Auto-curated collection: {name}\n"
                        "Generated by WAR SHORTS Pipeline"
                    ),
                    "defaultLanguage": "en",
                },
                "status": {"privacyStatus": "public"},
            },
        ).execute()
        playlist_id = result["id"]
        cache[name] = playlist_id
        _save_playlist_cache(cache)
        print(f"[playlist] Yeni playlist oluşturuldu: '{name}' → {playlist_id}")
        return playlist_id
    except Exception as e:
        print(f"[playlist] Playlist oluşturulamadı '{name}': {e}")
        return None


def _pick_playlist(title: str, tags: list[str]) -> str:
    """Başlık ve tag'lere göre en uygun playlist adını döndürür."""
    combined = (title + " " + " ".join(tags)).lower()
    for rule in PLAYLIST_RULES:
        if not rule["keywords"]:
            continue
        for kw in rule["keywords"]:
            if kw in combined:
                return rule["name"]
    return PLAYLIST_RULES[-1]["name"]  # Varsayılan


def add_to_playlist(video_id: str, script: dict) -> bool:
    """
    Videoyu uygun playlist'e ekler.

    Args:
        video_id: YouTube video ID
        script: Script dict (title + tags kullanılır)

    Returns:
        True if successful
    """
    if not YOUTUBE_AVAILABLE:
        print("[playlist] google-api-python-client kurulu değil.")
        return False

    title = script.get("title", "")
    tags = script.get("tags", [])
    playlist_name = _pick_playlist(title, tags)

    print(f"[playlist] Playlist seçildi: '{playlist_name}'")

    try:
        creds = _get_credentials()
        youtube = build("youtube", "v3", credentials=creds)
        cache = _load_playlist_cache()

        playlist_id = _get_or_create_playlist(youtube, playlist_name, cache)
        if not playlist_id:
            return False

        # Videoya ekle
        youtube.playlistItems().insert(
            part="snippet",
            body={
                "snippet": {
                    "playlistId": playlist_id,
                    "resourceId": {
                        "kind": "youtube#video",
                        "videoId": video_id,
                    },
                }
            },
        ).execute()

        print(f"[playlist] Video eklendi: {video_id} → '{playlist_name}' ({playlist_id})")
        return True

    except Exception as e:
        print(f"[playlist] Video eklenemedi (kritik değil): {e}")
        return False


if __name__ == "__main__":
    import sys
    vid = sys.argv[1] if len(sys.argv) > 1 else input("Video ID: ")
    test_script = {
        "title": "What if Rome Never Fell?",
        "tags": ["rome", "whatif", "history"],
    }
    add_to_playlist(vid, test_script)
